services:
  - type: web
    name: hospital-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        fromValue: 'mongodb+srv://user:pass@cluster.mongodb.net/db'
      - key: JWT_SECRET
        sync: false

  - type: web
    name: hospital-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishDir: dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: hospital-backend
          property: host
